[project]
name = "memu-server"
version = "0.1.0"
description = "backend wrapper for memU"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "memu-py==0.6.0",
]

[dependency-groups]
dev = [
    "requests>=2.32.5",
]
